### ISSUE TITLE
关于数据类型的询问

### ISSUE THREAD

**Issue by SupritYoung** [NUSTM/MEMD-ABSA#3]
您好！我在论文中看到 MEME-ABSA 是一个多领域、多任务的数据集，但是在Github中只看到了关于四元组 ASQP 的数据，没有看到关于三元组ASTE、二元组ASPE的数据。请问这些数据可以提供嘛？我们目前正在进行关于 ABSA 的研究，期待您的回复。

**Comment by blhoy** [comment]
您好，三元组和二元组的数据均可由四元组数据简化（合并以及是否保留隐式标注）、去重得到。

**Comment by SupritYoung** [comment]
请问可以直接开源数据或者代码嘛，我担心我这里处理不规范，复现结果和你们论文不一致。

**Comment by SupritYoung** [comment]
请问方面是不可为 NULL 的对吧，如果一个句子中只有隐式方面，应该如何处理呢？

**Comment by blhoy** [comment]
> 请问方面是不可为 NULL 的对吧，如果一个句子中只有隐式方面，应该如何处理呢？

对于ABSC、AOPE任务，方面为NULL时会退化为句子级的情感标签，测试集只包含显式方面的样例（table 3 4）；考虑到AOS任务可以有隐式opinion，ACOS任务可以有隐式opinion和隐式方面，我们将测试集分为两部分：只包含显式样例（table 5 7）和包含所有样例（去掉只有隐式标签的样例，保留句子），相应结果在table 9中。

**Comment by SupritYoung** [comment]
感谢您的耐心解答，我们已经处理好数据。
